# GitHub Pages configuration
# This ensures index.html is served as the default page

# Disable Jekyll processing (redundant with .nojekyll but explicit)
plugins: []
safe: true

# Include all files
include:
  - "_*"
  - ".nojekyll"

# Exclude documentation from the site
exclude:
  - "DOCUMENTATION.md"
  - "DEPLOY_INSTRUCTIONS.md"
  - "*.bat"
  - "bin/"
